#!/usr/bin/env bash
#
# bash-project: generate BASH projects from a template.
# Author: Curtis K
# Github: https://github.com/curtis86

# BASH MODES
set -u
set -o pipefail

# SCRIPT FUNCTIONS
abrt() { echo "ERROR: $@ -- exiting." 1>&2 ; exit 1 ;}
usage() { echo -e "\nUsage: $( basename $0 ) <project_name> <project_version> <project_parent_directory>" ;}
test_access() { test_target="$1" ; [ ! -w "${test_target}" ] && abrt "Unable to access ${test_target}" ;}

readonly REQ_ARGS=3 ; [ $# -ne ${REQ_ARGS} ] && usage && exit 1
readonly home_dir="$( cd "$( dirname $0 )" ; pwd )"
readonly project_template_file="${home_dir}/bash-template.txt" ; test_access "${project_template_file}"

project_name="$1"
project_version="$2"
project_parent_directory="$3"

main(){
  echo
  echo -n "Are you sure you want to create project ${project_name} ${project_version} in ${project_parent_directory} (${project_parent_directory}/${project_name}/) ? <y/n> "
  read create_confirmation < /dev/tty
  create_confirmation="$( echo "${create_confirmation}" | tr '[A-Z]' '[a-z]' )"
  if [ "${create_confirmation}" != "y" ]; then
    echo "Exiting at user request."
    exit 0
  fi

  test_slash_in_project_name="$( echo "${project_name}" | grep '/' )"
  [ -n "${test_slash_in_project_name}" ] && abrt "Please do not use the / character in project names"

  test_access "${project_parent_directory}"
  project_directory="${project_parent_directory}/${project_name}"
  [ -d "${project_directory}" ] && abrt "Project directory ${project_directory} already exists"

  echo
  echo "Creating project... "
  mkdir "${project_directory}"
  project_file="${project_directory}/${project_name}"
  cp "${project_template_file}" "${project_file}"
  chmod +x "${project_file}"
  sed -i "s/PROJECT_NAME/${project_name}/g" "${project_file}" 2>/dev/null || sed -i '' "s/PROJECT_NAME/${project_name}/g" "${project_file}"
  sed -i "s/PROJECT_VERSION/${project_version}/g" "${project_file}" 2>/dev/null || sed -i '' "s/PROJECT_VERSION/${project_version}/g" "${project_file}"
  echo
  echo "Completed. Project created in ${project_directory}."

}
main $@
